### ISSUE TITLE
T1 - ¿Tiende a crecer el tamaño de las distribuciones a lo largo del tiempo?

### ISSUE THREAD

**Issue by joszamama** [joszamama/linux-distros-analysis#20]

**Comment by diemonvaz** [comment]
Tengo los cambios en local...
Hago resumen:

Usaremos una regresión lineal para modelar la relación entre el tamaño de la distribución y el año. 
Si el coeficiente de regresión es positivo, entonces hay una tendencia creciente en el tamaño de la distribución a lo largo del tiempo

Tras ver que es negativo lo anterior, por lo cual no tiende a subir, queremos comprobarlo con otra técnica
Usaremos un análisis de series de tiempo para modelar la evolución del tamaño de las distribuciones a lo largo del tiempo

Por último, el análisis de regresión no lineal se utilizó para examinar si existe una tendencia en el tamaño de las distribuciones de paquetes a lo largo del tiempo. 
El modelo ajustado se puede usar para hacer predicciones sobre el tamaño de las distribuciones en el futuro y para evaluar si la tendencia observada en los datos es significativa.

**Comment by diemonvaz** [comment]
Ya está todo subido a la rama. Finalmente hemos realizado:

Un análisis de tiempo, al verlo poco claro tiramos a una regresión lineal

Con esto comprobamos lo que esperábamos... AUMENTA RESPECTO AL TIEMPO
