### ISSUE TITLE
V4 - Análisis de correlación entre el tamaño de las versiones de la distribución Ubuntu. Diagrama de cajas.

### ISSUE THREAD

**Issue by joszamama** [joszamama/linux-distros-analysis#26]

**Comment by diemonvaz** [comment]
He realizado primero un pequeño preprocesamiento.
Luego un Cálculo de la correlación. Para obtener un valor numérico que indica la fuerza y dirección de la relación entre las variables.
Para dejarlo mostrado en un mapa de calor.

Más tarde he identificado los paquetes más grandes, para dejarlos marcados.

Y por último, lo más interesante, el diagrama de cajas visualizado.


Todo está en la rama **diemonvaz**
